# Generated by Django 4.0.4 on 2022-06-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_empresa_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
