# Generated by Django 4.0.4 on 2022-06-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empresa_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cidade',
        ),
    ]
