# Generated by Django 4.0.4 on 2022-06-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_cidade_empresa_cidade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='cidade',
        ),
        migrations.AddField(
            model_name='local',
            name='cidade_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
