# Generated by Django 4.0 on 2022-06-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_produto_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
