# Generated by Django 4.0 on 2022-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contato',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
